@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
SHOW_PERSON_PORTRAIT()
LAYOUT_LEFT_RIGHT()
LAYOUT_WITH_LEGEND()

Person(user, "Usuário", "Usuário que interage com o sistema")
ContainerQueue(armazenamento, "Banco de dados", "Database Schema", "Armazena o arquivo importado")

rectangle system {
    Container(frontend, "Frontend", "Web applications", "Aplicação web em que o usuario interage e visualiza os resultados")
    Container(backend, "Backend", "Python", "Módulos que executam as solicitações do usuário, acessa o banco de dados e devolve os resultados para o frontend")
    user -- (frontend)
    (frontend) .> (backend)
    (backend) .> (frontend)
    Rel(backend, armazenamento, "Lê e escreve em")
}
@enduml


#Rel(user, system, "Usa")
#Rel(system, frontend, "Usa")
#Rel(frontend, backend, "Usa")
#Rel(backend, armazenamento, "Lê e escreve em")
#(frontend) .> (backend) : include
#(backend) .> (armazenamento) : extends